stages:
    - test

postman_tests:
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman
        - npm install -g newman-reporter-htmlextra
        - newman run collection.json --reporters=cli,htmlextra --reporter-htmlextra-export newman-report.html 
    artifacts:
        when: always
        paths:
            - newman-report.html        
